### PR TITLE
Formula cleanup, better checksums and fixed URL for epel7

### PR DESCRIPTION
**Pull request by ixs**
Reworked PR #23 and updated it to current head.
Fixed the epel7 URL as described in issue #42.

### CODE REVIEW

**Comment by javierbertoli** [comment]
@ixs I see you removed the possibility of using `testing` repos. Any particular reason?

**Comment by ixs** [comment]
@javierbertoli nothing particular. I just took the previous PR which seemed dead. Must have missed the testing option.

Gimme a bit of time, I'll update the PR.

**Comment by ixs** [comment]
Re-added the support for testing which accidentally got dropped.

**Comment by javierbertoli** [comment]
Thanks @ixs @aboe76 !

**Pull request merged**
