### PR TITLE
EPEL release 7-7 and pillar support

### PR DESCRIPTION
**Pull request by eliasp**
This allows to quickly define a newer EPEL release than hardcoded in the Formula by simply setting the Pillar `epel:release`.

Besides that, it updates the default release on RHEL/CentOS 7 to 7-7 (see also: #25, which would be obsoleted by this PR).

### CODE REVIEW

**Comment by gravyboat** [comment]
This looks good. Could you please add the `epel:release` value to the pillar.example?

**Comment by eliasp** [comment]
@gravyboat done

**Comment by eliasp** [comment]
Oups… wrong button ;) - re-opened

**Comment by gravyboat** [comment]
Thanks!

**Pull request merged**
