### PR TITLE
fix(map.jinja): update to `epel-release-8-11.el8.noarch.rpm`

### PR DESCRIPTION
**Pull request by Niyakiy**
A simple reflection of the EPEL release version in the upstream repo.

### CODE REVIEW

**Review by javierbertoli — CHANGES_REQUESTED** [review]
@Niyakiy thanks for this PR. It's ok, just failing some commit-lint checks. We are using [semantic-versioning](https://semver.org) which depends on the [commit's message format](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines) to update.

In this case, if you just amend your message to something like
```
fix(map.jinja): update to `epel-release-8-11.el8.noarch.rpm`
```
it will be ready to merge.

Thanks!

**Comment by Niyakiy** [comment]
sure @javierbertoli, thanks for the heads up. I've reworded the commit.

btw - is there any possibility to implement some logic to perform lookups for the latest available RPM to avoid such situations?
It'll be nice to get the most recent version installed.

**Comment by javierbertoli** [comment]
> sure @javierbertoli, thanks for the heads up. I've reworded the commit.
> 
> btw - is there any possibility to implement some logic to perform lookups for the latest available RPM to avoid such situations?
> It'll be nice to get the most recent version installed.

I usually install the `epel-release` package from the distro repo, but I understand it might be different for some other distros. However, in [the EPEL repo's page](https://fedoraproject.org/wiki/EPEL) they suggest you just install the `epel-release-latest-<version>.noarch.rpm` package, so it might be refactored to install that package with a remote package resource?

**Review by javierbertoli — APPROVED** [review]

**Comment by javierbertoli** [comment]
Thanks, @Niyakiy !

**Comment by Niyakiy** [comment]
thanks for the quick turnaround @javierbertoli.

**Pull request merged**
