### PR TITLE
osmajorrelease is int instead of str since 2017.7.1

### LINKED ISSUE #58: [BUG]  EPEL is not getting installed in rhel 8

### PR DESCRIPTION
**Pull request by itscaro**
Cf type changed for osmajorrelease: https://github.com/saltstack/salt/blob/v2017.7.1/salt/grains/core.py#L1675

After digging a bit, I found the reason why this formula is backward compatible, there is type trying in this function which is used by `filter_by` function defined in `salt/modules/grains.py`
https://github.com/saltstack/salt/blob/4669f1373a5524fd22a45ff730717a382272f753/salt/utils/data.py#L815-L839

I encountered this issue when using `salt-ssh` which uses another version of `filter_by` function provided by `salt/client/ssh/wrapper/grains.py`, which is type-enforced.

Fixes #58

### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

Yes for version < 2017.7

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
Thanks for this PR, @itscaro.  I fixed the hyperlink you provided since it was a `404`.

I was about to suggest how to get the `commitlint` passing but I see you've managed that!  So just the tests now and this can be merged.

**Comment by myii** [comment]
OK, the link for CentOS 8 needs updating to:

* https://mirrors.ukfast.co.uk/sites/dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/e/epel-release-8-10.el8.noarch.rpm

Would you mind adding that as well, @itscaro?

**Comment by myii** [comment]
@itscaro Something like the following to pass the `commitlint`:

```
fix(map.jinja): update link to `rpm` for `EPEL-8`
```

**Comment by itscaro** [comment]
> OK, the link for CentOS 8 needs updating to:
> 
> * https://mirrors.ukfast.co.uk/sites/dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/e/epel-release-8-10.el8.noarch.rpm
> 
> Would you mind adding that as well, @itscaro?

I saw the error in Gitlab and push another commit in this PR.

**Comment by myii** [comment]
> I saw the error in Gitlab and push another commit in this PR.

@itscaro Thanks, we just need _all_ of the commits to make `commitlint` happy!  So for that last commit, please change the commit title to:

```diff
-update to epel-release-8-10.el8.noarch.rpm
+fix(map.jinja): update to `epel-release-8-10.el8.noarch.rpm`
```

**Comment by itscaro** [comment]
> Thanks for this PR, @itscaro. I fixed the hyperlink you provided since it was a `404`.
> 
> I was about to suggest how to get the `commitlint` passing but I see you've managed that! So just the tests now and this can be merged.

Yes I did not realized that I was in a forked repo :)

**Comment by myii** [comment]
> Sorry again for the lint errors

No problem at all, it took us some time to get used to it as well!  If GitLab passes, then we'll merge this.  Don't worry about the other `commitlint` error here in GitHub Actions.

**Comment by myii** [comment]
Merged, thanks for the fix, @itscaro!

**Comment by itscaro** [comment]
> Merged, thanks for the fix, @itscaro!

@myii the changelog contains bad urls, must be me with my comments full of urls

**Comment by myii** [comment]
> @myii the changelog contains bad urls, must be me with my comments full of urls

No, this is a known bug that I've reported:

* https://github.com/conventional-changelog/conventional-changelog/issues/415

Don't worry, it's not your fault.  We don't have to open another PR to fix it, the main information we need is there and people can click the hyperlinks to see the commits.  Thanks again!

**Pull request merged**
